using System;
int eno;
string ename;
double esal;
double epf;
string egrade;
bool ews;
Console.Write("enter eno..:");
eno = Convert.ToInt32(Console.ReadLine());
Console.Write("enter ename..:");
ename = Console.ReadLine();
Console.Write("enter esal..:");
esal = Convert.ToDouble(Console.ReadLine());
Console.Write("enter epf..:");
epf = Convert.ToDouble(Console.ReadLine());
Console.Write("enter egrade..:");
egrade = Console.ReadLine();
Console.Write("enter ework status(true/false):");
ews = Convert.ToBoolean(Console.ReadLine());
System.Console.Clear();
System.Console.WriteLine("...........................");
System.Console.WriteLine("Employee Details");
System.Console.WriteLine("...........................");
System.Console.WriteLine("Number="+eno);
System.Console.WriteLine("Name=" + ename);
System.Console.WriteLine("Salary=" + esal);
System.Console.WriteLine("Provident fund=" + epf);
System.Console.WriteLine("Grade=" + egrade);
System.Console.WriteLine("Work Status=" + ews);
System.Console.WriteLine("...........................");
