using System;
int sno;
String sname;
int sclass;
String ssec;
int m1, m2, m3, m4, m5, m6, tot;
float avg;
System.Console.Clear();
System.Console.Write("Enter sno:");
sno = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter sname:");
sname = Console.ReadLine();
System.Console.Write("Enter sclass:");
sclass = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter ssec:");
ssec = Console.ReadLine();
System.Console.Write("Enter m1:");
m1 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter m2:");
m2 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter m3:");
m3 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter m4:");
m4 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter m5:");
m5 = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Enter m6:");
m6 = Convert.ToInt32(Console.ReadLine());
tot = m1 + m2 + m3 + m4 + m5 + m6;
avg = tot / 6;
System.Console.Clear();
System.Console.WriteLine("..........................");
System.Console.WriteLine("sno=" + sno + "\t\t" + "sname=" + sname);
System.Console.WriteLine("sclass=" + sclass + "\t\t" + "ssec=" + ssec);
System.Console.WriteLine("**************************");
System.Console.WriteLine("m1=" + m1 + "\t" + "m2=" + m2 + "\t" + "m3=" + m3);
System.Console.WriteLine("m4=" + m4 + "\t" + "m5=" + m5 + "\t" + "m6=" + m6);
System.Console.WriteLine("**************************");
System.Console.WriteLine("Total Marks="+tot);
System.Console.WriteLine("Average=" + avg);
System.Console.WriteLine("..........................");


